### PR TITLE
feat(api): support transfers to BLS public keys

### PR DESCRIPTION
**Pull request by bochaco**

### CODE REVIEW

**Comment by b-zee** [comment]
@bochaco 

Is it deliberate that the work of #756 was undone with this PR?

https://github.com/maidsafe/sn_api/pull/776/commits/815ce6f0a0c7363779886b86c880df897b520843#diff-470737e274118012235c9c30bd79c2ed65d0a790037ad4782cabcc27b6df5fd3R98

**Comment by bochaco** [comment]
I remember having issues when working on it, so not necessarily, if we can have a ref in the arg we can make it back again

**Comment by b-zee** [comment]
Was there anything specific that introduced the issue? I'd happily introduce it back again, because transferring ownership for the key is problematic as you can't clone it (and probably should not due to security)...

**Comment by bochaco** [comment]
Yeah, go ahead, it'll be good to change it back, I think the issue was with some of the data-types APIs for creating a keypair out of it.

**Comment by b-zee** [comment]
I've made a topic on the dev forum about it. I think there are more things here to take into account.

https://forum.safedev.org/t/private-key-in-ram/3011?u=bzee

I'm also curious about the opinion from @madadam (although I don't know if he's still working on the code).

**Pull request merged**
